### ISSUE TITLE
PyFBA with python3

### ISSUE THREAD

**Issue by annazhukova** [linsalrob/PyFBA#3]
Dear PyFBA developers,

Does PyFBA work with Python 3? When I try to install it from PyPI:
```bash
pip install pyfba
```
or clone from github and run tests
```bash
git clone https://github.com/linsalrob/PyFBA.git
cd PyFBA
python3 setup.py test
```
I get the same following error:
```bash
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    import PyFBA
  File "..../PyFBA/PyFBA/__init__.py", line 3, in <module>
    import fba
ImportError: No module named 'fba'
```

Thanks,
Anna

**Comment by linsalrob** [comment]
Hi Anna

We have been developing a [python3 version](https://github.com/linsalrob/PyFBA/tree/python3) and will come out with a release in the next day or two. In the meantime, you can easily get to it, by switching branches in git.

First, move to the git repository, and then switch branch:
```
cd PyFBA
git checkout python3
```

and then run the tests:

```
nosetests-3.5 PyFBA/tests/
python3.5 setup.py test
```

Please let us know if that works.

Rob

**Comment by annazhukova** [comment]
Hi Rob,

Thank you very much for your quick reply.
I have switched to the python3 branch and everything works now.

Cheers,
Anna
